version: 2
jobs:
  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - run:
          name: "Publish Release on GitHub"
          command: |
            set -u
            set -o pipefail
            LATEST_VERSION=$(curl --silent "https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
            [  -z "$LATEST_VERSION" ] && LATEST_VERSION="0.0.0"
            VERSION=$(echo $LATEST_VERSION | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
            echo ${VERSION} > VERSION
            ghr \
              -t ${GITHUB_TOKEN} \
              -u ${CIRCLE_PROJECT_USERNAME} \
              -r ${CIRCLE_PROJECT_REPONAME} \
              -c ${CIRCLE_SHA1} -delete \
              ${VERSION} ./VERSION
workflows:
  version: 2
  publish-release:
    - jobs:
      - publish-github-release:
          filters:
            branches:
              only: master
