jobs:
- name: test
  plan:
  - get: terraform-aws-prowler-monitoring-test
    trigger: true
    version: every
  - get: terraform-aws-prowler-monitoring
  - put: terraform-aws-prowler-monitoring-test
    params:
      repository: terraform-aws-prowler-monitoring
      merge: true
  - .: (( inject meta.plan.terraform-bootstrap ))
    input_mapping:
      terraform-aws-prowler-monitoring: terraform-aws-prowler-monitoring-test
  - task: terraform-terratest
    .: (( inject meta.plan.terraform-terratest ))
    input_mapping:
      terraform-aws-prowler-monitoring: terraform-aws-prowler-monitoring-test
  - put: terraform-aws-prowler-monitoring
    params:
      repository: terraform-aws-prowler-monitoring-test
      merge: true
  .: (( inject meta.plan.notify ))
